name       : tomahawk
version    : 0.8.4
release    : 9
source     :
    - git|https://github.com/tomahawk-player/tomahawk.git : ad59c9acde5bdc6dfc715e09764fd89b476d3d1d
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Tomahawk is a free multi-source and cross-platform music player.
description: |
    liblastfm is a collection of libraries to help you integrate Last.fm services into your rich desktop software. It is officially supported software developed by Last.fm staff.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(gnutls)
    - pkgconfig(libKF5Attica)
    - pkgconfig(liblucene++)
    - pkgconfig(libsparsehash)
    - pkgconfig(libvlc)
    - pkgconfig(x11)
    - pkgconfig(qca2-qt5)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - extra-cmake-modules
    - libboost-devel
    - liblastfm-devel
    - qtkeychain-devel
    - quazip-devel
setup      : |
    sed -i 's/QTKEYCHAIN_FOUND/Qt5Keychain_FOUND/' CMakeLists.txt


    %cmake -DBUILD_WITH_QT4=OFF \
           -DBUILD_HATCHET=OFF \
           -DBUILD_RELEASE=ON \
           -DWITH_KDE=OFF .
build      : |
    %make
install    : |
    %make_install
