name       : tomahawk
version    : 0.8.4
release    : 7
source     :
    - git|https://github.com/tomahawk-player/tomahawk.git : 97a407f83701ee2343e4826043c311c03fe5675b
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Tomahawk is a free multi-source and cross-platform music player.
description: |
    Tomahawk is a free multi-source and cross-platform music player.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(gnutls)
    - pkgconfig(libKF5Attica)
    - pkgconfig(liblucene++)
    - pkgconfig(libsparsehash)
    - pkgconfig(libvlc)
    - pkgconfig(qca2-qt5)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - extra-cmake-modules
    - libboost-devel
    - liblastfm-devel
    - qtkeychain-devel
    - quazip-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Override-liblastfm-paths.patch
    %patch -p1 < $pkgfiles/0001-Resolve-incorrect-paths-for-lastfm-usage.patch

    %cmake -DBUILD_WITH_QT4=OFF \
           -DBUILD_HATCHET=OFF \
           -DBUILD_RELEASE=ON \
           -DWITH_KDE=OFF .
build      : |
    %make
install    : |
    %make_install
